version: '3.7'
services:
    vite-react-app:
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
    express:
        build:
            context: ./back
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
