apiVersion: apps/v1
kind: Deployment
metadata:
    name: react-front
    labels:
        app: react-front
spec:
    replicas: 3
    selector:
        matchLabels:
            app: react-front
            tier: front
    template:
        metadata:
            labels:
                app: react-front
                tier: front
        spec:
            containers:
                - name: react-front
                  image: docker.io/leejaehyuck9/hw2_vite-react-app
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: react-front
spec:
    type: NodePort
    selector:
        app: react-front
        tier: front
    ports:
        - port: 3000
