apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-back
    labels:
        app: node-back
spec:
    replicas: 3
    selector:
        matchLabels:
            app: node-back
            tier: back
    template:
        metadata:
            labels:
                app: node-back
                tier: back
        spec:
            containers:
                - name: node-back
                  image: docker.io/leejaehyuck9/hw2_express
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
    name: node-back
spec:
    type: NodePort
    selector:
        app: node-back
        tier: back
    ports:
        - port: 3001
